name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build Docker images
    strategy:
        matrix:
          include:
            - platform: amd64
              runner: ubuntu-latest
            - platform: arm64
              runner: ubuntu-22.04-arm # This is self-hosted, change later...
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: prmoorevoltron/flight-sql:latest-${{ matrix.platform }}
          with:
            no-cache
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab

  update-image-manifest:
    name: Update DockerHub image manifest to include all built platforms
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
          inputs: prmoorevoltron/flight-sql:latest
          images: prmoorevoltron/flight-sql:latest-amd64,prmoorevoltron/flight-sql:latest-arm64
          push: true
